{% set name = "sybil" %}
{% set version = "9.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/simplistix/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f872f3df3640eb001ce70432aa9d4a90cf068884b482702bdc10e966765a46e7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# Tests disabled -> E   ModuleNotFoundError: No module named 'seedir' (not in the main channel) -> https://pypi.org/project/seedir
test:
  imports:
    - sybil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simplistix/sybil
  summary: Automated testing for the examples in your documentation.
  description: |
    This library provides a way to check examples in your code and documentation
    by parsing them from their source and evaluating the parsed examples as part
    of your normal test run. Integration is provided for the main Python test
    runners.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  doc_url: https://sybil.readthedocs.io
  dev_url: https://github.com/simplistix/sybil

extra:
  recipe-maintainers:
    - joaander
