{% set name = "sybil" %}
{% set version = "5.0.2" %}
{% set sha256 = "127500e510ba3325b3a613783171040a1d3d20866ac16c9af42af96c69cc7dec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - sybil
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/simplistix/sybil
  summary: 'Automated testing for the examples in your documentation.'
  description: |
    This library provides a way to check examples in your code and documentation
    by parsing them from their source and evaluating the parsed examples as part
    of your normal test run. Integration is provided for the main Python test
    runners.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://sybil.readthedocs.io/
  dev_url: https://github.com/simplistix/sybil

extra:
  recipe-maintainers:
    - joaander
